@extends('master')
@section('usuario', $User)
@section('conteudo')
<style>
  
</style>
<div class="c19">
   <p class="c2"><span class="c8 c3">1- Introdu&ccedil;&atilde;o</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c0"><span class="c4">O Sistema de Informa&ccedil;&atilde;o para Agricultura Familiar (SIAF) &eacute; um sistema de gerenciamento pensado para os agricultores em transi&ccedil;&atilde;o agroecol&oacute;gica de Corumb&aacute; e Lad&aacute;rio, desenvolvido pela F&aacute;brica de Software da UFMS - C&acirc;mpus do Pantanal. O SIAF tem como objetivos principais auxiliar o agricultor na gest&atilde;o e armazenamento das atividades executadas em sua propriedade, fornecer um acompanhamento das vendas dos produtos para os consumidores, apoiar o agricultor fornecendo com informa&ccedil;&otilde;es significativas sobre sua planta&ccedil;&atilde;o, previs&otilde;es clim&aacute;ticas e automatizar a cria&ccedil;&atilde;o de relat&oacute;rios e documentos necess&aacute;rios.</span></p>
   <p class="c0"><span class="c4">Este manual tem como objetivo auxiliar o agricultor na utiliza&ccedil;&atilde;o do Sistema de Informa&ccedil;&otilde;es para Agricultura Familiar. </span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c8 c3">2- Cadastro</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span>Para utilizar o sistema, o agricultor precisa se cadastrar no site clicando em &ldquo;</span><span>Ainda n&atilde;o tem uma conta? Voc&ecirc; pode se cadastrar!&rdquo;</span><span class="c4">&nbsp;conforme mostrado na Figura.</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 350.67px;"><img alt="" src="images/imagesManual/image31.png" style="width: 720.20px; height: 350.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c7 c18"><span class="c12"></span></p>
   <p class="c7 c18"><span class="c12"></span></p>
   <p class="c0"><span>No cadastro s&atilde;o armazenadas as informa&ccedil;&otilde;es pessoais do agricultor e de sua propriedade, al&eacute;m da senha que ser&aacute; utilizada para acessar o sistema. Os campos dever&atilde;o ser preenchidos com as informa&ccedil;&otilde;es necess&aacute;rias, sendo campos obrigat&oacute;rios os assinalados por um asterisco destacado (</span><span class="c21">*</span><span class="c4">) e os demais s&atilde;o opcionais.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 535.00px; height: 509.00px;"><img alt="" src="images/imagesManual/image6.png" style="width: 535.00px; height: 509.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c8 c3">3- Login</span></p>
   <p class="c2"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Depois de cadastrado o agricultor retornar&aacute; &agrave; tela inicial, onde poder&aacute; se autenticar no sistema utilizando o CPF e a senha preenchidas durante o cadastro. </span></p>
   <p class="c0"><span class="c4">Caso o agricultor tenha problemas na autentica&ccedil;&atilde;o ele poder&aacute; requisitar uma recupera&ccedil;&atilde;o de senha. A recupera&ccedil;&atilde;o de senha exige que o email tenha sido informado durante o cadastro, pois o sistema envia por email o link onde o agricultor dever&aacute; informar uma senha nova. </span></p>
   <p class="c7 c18"><span class="c4"></span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c8 c3">4- O SIAF </span></p>
   <p class="c0"><span class="c4">Depois que o agricultor se autenticar ter&aacute; acesso &agrave; todas as op&ccedil;&otilde;es do sistema. No sistema o agricultor poder&aacute; acessar menus que o auxiliar&atilde;o na gest&atilde;o da propriedade. H&aacute; ainda o manual e op&ccedil;&atilde;o de atualiza&ccedil;&atilde;o do perfil de usu&aacute;rio do sistema.</span></p>
   <p class="c2"><span class="c8 c3">4.1- Menus</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">As op&ccedil;&otilde;es dispon&iacute;veis no sistema s&atilde;o detalhadas nas subse&ccedil;&otilde;es a seguir.</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.1 &nbsp;</span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 52.70px; height: 52.70px;"><img alt="" src="images/imagesManual/image33.png" style="width: 52.70px; height: 52.70px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c8 c3">In&iacute;cio</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">O menu in&iacute;cio permite ao agricultor retornar &agrave; tela principal do sistema de qualquer outra tela que ele esteja. Nele &eacute; poss&iacute;vel ver a previs&atilde;o meteorol&oacute;gica da semana de acordo com a cidade em que sua &nbsp;propriedade est&aacute; localizada.</span></p>
   <p class="c11"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 345.33px;"><img alt="" src="images/imagesManual/image7.png" style="width: 720.20px; height: 345.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1"><span class="c8 c3"></span></p>
   <p class="c2"><span class="c3">4.1.2 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 93.00px; height: 93.00px;"><img alt="" src="images/imagesManual/image28.png" style="width: 93.00px; height: 93.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c8 c3">&nbsp;Propriedade</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">No menu propriedade o agricultor pode ver as informa&ccedil;&otilde;es sobre a sua propriedade, os talh&otilde;es criados e produtos que est&atilde;o sendo produzidos. Os dados de propriedade podem somente ser editados.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 297.33px;"><img alt="" src="images/imagesManual/image16.png" style="width: 720.20px; height: 297.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c21">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c0"><span class="c4">Os talh&otilde;es da propriedade podem ser cadastrados, editados ou exclu&iacute;dos. A exclus&atilde;o s&oacute; &eacute; permitida caso n&atilde;o haja plantio associado ao talh&atilde;o.</span></p>
   <p class="c7 c10"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 624.00px; height: 230.00px;"><img alt="" src="images/imagesManual/image20.png" style="width: 624.00px; height: 230.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c0"><span>O</span><span>s produtos que est&atilde;o em produ&ccedil;&atilde;o na propriedade podem ser cadastrados ou editados. Caso algum produto deixe de ser produzido &eacute; poss&iacute;vel </span><span>desativ&aacute;-lo</span><span class="c4">&nbsp;na tela de edi&ccedil;&atilde;o. </span></p>
   <p class="c7 c10"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 624.00px; height: 328.00px;"><img alt="" src="images/imagesManual/image10.png" style="width: 624.00px; height: 328.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c2"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c2"><span class="c3">4.1.3 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 66.00px; height: 66.00px;"><img alt="" src="images/imagesManual/image23.png" style="width: 66.00px; height: 66.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span class="c8 c3">Plantio</span></p>
   <p class="c2"><span class="c3">&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">No menu plantio o agricultor pode ver as informa&ccedil;&otilde;es sobre o cultivo em sua propriedade. Para cadastrar um plantio &eacute; necess&aacute;rio que o talh&atilde;o e o produto estejam cadastrados. </span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 152.00px;"><img alt="" src="images/imagesManual/image8.png" style="width: 720.20px; height: 152.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c21">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c11"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&Eacute; poss&iacute;vel editar ou excluir um plantio. A exclus&atilde;o s&oacute; &eacute; permitida enquanto n&atilde;o houver um manejo registrado para o item.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 626.00px; height: 285.00px;"><img alt="" src="images/imagesManual/image36.png" style="width: 626.00px; height: 285.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.4 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 65.00px; height: 65.00px;"><img alt="" src="images/imagesManual/image11.png" style="width: 65.00px; height: 65.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span class="c8 c3">Manejo</span></p>
   <p class="c0"><span class="c4">No menu manejo s&atilde;o registrados todos os manejos realizados no cultivo de produtos plantados nos talh&otilde;es da propriedade. Os campos necess&aacute;rios para o cadastro de um manejo s&atilde;o apresentados na figura abaixo. &Eacute; necess&aacute;rio que haja plantio cadastrado para o registro de manejo.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 614.00px; height: 252.00px;"><img alt="" src="images/imagesManual/image9.png" style="width: 614.00px; height: 252.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c2"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ao incluir um manejo do tipo colheita &eacute; poss&iacute;vel que o sistema insira automaticamente o produto no estoque. Para isto basta acessar a op&ccedil;&atilde;o estocar, conforme mostra a figura abaixo. Ap&oacute;s essa opera&ccedil;&atilde;o n&atilde;o &eacute; poss&iacute;vel realizar edi&ccedil;&otilde;es ou exclus&atilde;o do manejo.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 627.00px; height: 289.00px;"><img alt="" src="images/imagesManual/image29.png" style="width: 627.00px; height: 289.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c2"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;O agricultor poder&aacute; editar as informa&ccedil;&otilde;es de cada manejo ou exclu&iacute;-lo, desde que n&atilde;o esteja estocado.</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 236.00px;"><img alt="" src="images/imagesManual/image34.png" style="width: 720.20px; height: 236.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c2"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Os manejos dispon&iacute;veis para uso no sistema s&atilde;o:</span></p>
   <ul class="c17 lst-kix_d83vsikcc95y-0 start">
      <li class="c2 c15"><span class="c4">Capina</span></li>
      <li class="c2 c15"><span class="c4">Desbaste</span></li>
      <li class="c2 c15"><span class="c4">Rega</span></li>
      <li class="c2 c15"><span class="c4">Controle de pragas</span></li>
      <li class="c2 c15"><span class="c4">Aduba&ccedil;&atilde;o</span></li>
      <li class="c2 c15"><span class="c4">Ara&ccedil;&atilde;o</span></li>
   </ul>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.5 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 69.00px; height: 69.00px;"><img alt="" src="images/imagesManual/image13.png" style="width: 69.00px; height: 69.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span class="c8 c3">Estoque</span></p>
   <p class="c0"><span class="c4">No menu estoque s&atilde;o registrados todos os produtos colhidos/produzidos na propriedade. H&aacute; produtos que podem ser cadastrados diretamente, tais como os p&atilde;es, n&atilde;o plant&aacute;veis. Outros devem ser registrados desde o plantio, tais como alface. </span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 117.33px;"><img alt="" src="images/imagesManual/image17.png" style="width: 720.20px; height: 117.33px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10 c23"><span class="c12"></span></p>
   <p class="c0"><span class="c8 c22">Produtos n&atilde;o plant&aacute;veis</span></p>
   <p class="c0"><span class="c4">Para cadastrar diretamente no estoque &eacute; preciso que o produto esteja cadastrados como n&atilde;o plant&aacute;vel e esteja ativo. Os campos necess&aacute;rios para o cadastro de produto diretamente em estoque s&atilde;o apresentados na figura abaixo. </span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 625.00px; height: 223.00px;"><img alt="" src="images/imagesManual/image30.png" style="width: 625.00px; height: 223.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c0"><span class="c4">O agricultor poder&aacute; editar informa&ccedil;&otilde;es do estoque desde que n&atilde;o haja venda ou perda registradas para o item.</span></p>
   <p class="c0"><span class="c4">O estoque pode ainda ser atualizado caso haja perda de produtos. Neste caso, o agricultor pode registrar a perda preenchendo os campos exibidos na figura abaixo.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 620.00px; height: 291.00px;"><img alt="" src="images/imagesManual/image14.png" style="width: 620.00px; height: 291.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c7 c18"><span class="c4"></span></p>
   <p class="c7 c18"><span class="c4"></span></p>
   <p class="c0"><span class="c8 c22">Produtos plant&aacute;veis</span></p>
   <p class="c0"><span class="c4">Para cadastrar produtos plant&aacute;veis no estoque &eacute; preciso que o produto tenha sido registrado como colhido e enviado para estoque na tela de manejo. Os dados para o estoque vem diretamente a partir do manejo e com a op&ccedil;&atilde;o editar desabilitada. O agricultor n&atilde;o poder&aacute; editar informa&ccedil;&otilde;es do estoque para itens vindos via manejo.</span></p>
   <p class="c9"><span class="c4"></span></p>
   <p class="c0"><span class="c4">A perda de produtos plant&aacute;veis pode ser registrada preenchendo os campos exibidos na figura abaixo.</span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 625.00px; height: 293.00px;"><img alt="" src="images/imagesManual/image15.png" style="width: 625.00px; height: 293.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.6 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 73.70px; height: 73.70px;"><img alt="" src="images/imagesManual/image32.png" style="width: 73.70px; height: 73.70px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span class="c8 c3">Vendas</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span>No menu vendas s&atilde;o registradas todas as vendas realizadas pelo agricultor. Para cadastrar venda &eacute; preciso que os produtos estejam cadastrados no estoque.</span><span>&nbsp;</span><span class="c12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
   <p class="c1"><span class="c12"></span></p>
   <p class="c0"><span class="c4">Os campos necess&aacute;rios para o cadastro de uma venda s&atilde;o apresentados na figura abaixo. Ao salvar uma venda a quantidade de produtos em estoque &eacute; atualizada.</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 626.00px; height: 335.00px;"><img alt="" src="images/imagesManual/image1.png" style="width: 626.00px; height: 335.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c0"><span class="c4">Ap&oacute;s cadastrar suas vendas, o agricultor tem acesso a lista de vendas realizadas, como mostra a imagem a seguir.</span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 124.00px;"><img alt="" src="images/imagesManual/image21.png" style="width: 720.20px; height: 124.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c0"><span class="c4">O agricultor poder&aacute; editar informa&ccedil;&otilde;es ou excluir uma venda. Ao editar ou excluir uma venda a quantidade de produtos em estoque &eacute; atualizada.</span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c0"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 621.00px; height: 333.00px;"><img alt="" src="images/imagesManual/image22.png" style="width: 621.00px; height: 333.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.7 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 66.00px; height: 66.00px;"><img alt="" src="images/imagesManual/image25.png" style="width: 66.00px; height: 66.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp;</span><span class="c8 c3">Despesa</span></p>
   <p class="c0"><span class="c4">No menu despesa &eacute; registrado qualquer tipo de despesa do agricultor em sua propriedade.</span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 86.67px;"><img alt="" src="images/imagesManual/image18.png" style="width: 720.20px; height: 86.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c0"><span class="c4">Os campos necess&aacute;rios para o cadastro de uma despesa s&atilde;o apresentados na figura abaixo.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 624.00px; height: 322.00px;"><img alt="" src="images/imagesManual/image19.png" style="width: 624.00px; height: 322.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c0"><span>O agricultor poder&aacute; editar as informa&ccedil;&otilde;es de cada despesa ou exclu&iacute;-la.</span></p>
   <p class="c2"><span class="c3">4.1.8 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 64.00px; height: 64.00px;"><img alt="" src="images/imagesManual/image26.png" style="width: 64.00px; height: 64.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c8 c3">&nbsp;Investimento</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">No menu investimento &eacute; registrado qualquer tipo de investimento feito pelo agricultor em sua propriedade.</span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 86.67px;"><img alt="" src="images/imagesManual/image2.png" style="width: 720.20px; height: 86.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c1 c10 c23"><span class="c12"></span></p>
   <p class="c0"><span class="c4">Os campos necess&aacute;rios para o cadastro de um investimento s&atilde;o apresentados na figura abaixo.</span></p>
   <p class="c7"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 626.00px; height: 321.00px;"><img alt="" src="images/imagesManual/image12.png" style="width: 626.00px; height: 321.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c0"><span class="c4">O agricultor poder&aacute; editar as informa&ccedil;&otilde;es de cada investimento ou exclu&iacute;-lo.</span></p>
   <p class="c1"><span class="c8 c3"></span></p>
   <p class="c2"><span class="c3">4.1.9 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 66.00px; height: 66.00px;"><img alt="" src="images/imagesManual/image27.png" style="width: 66.00px; height: 66.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp; </span><span class="c8 c3">Relat&oacute;rio</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">No menu relat&oacute;rio o agricultor poder&aacute; acompanhar e visualizar de forma mais completa todas as informa&ccedil;&otilde;es de sua propriedade. Os relat&oacute;rios dispon&iacute;veis s&atilde;o detalhados na sequ&ecirc;ncia.</span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 720.20px; height: 144.00px;"><img alt="" src="images/imagesManual/image5.png" style="width: 720.20px; height: 144.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c11 c10"><span>&Eacute; obrigat&oacute;rio informar dd/mm/aaaa de in&iacute;cio e fim do per&iacute;odo;</span></p>
   <p class="c1 c16"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2 start" start="1">
      <li class="c6"><span class="c4">Listar vendas realizadas por per&iacute;odo;</span></li>
   </ol>
   <p class="c11"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exibe as seguintes informa&ccedil;&otilde;es referente &agrave;s vendas ocorridas dentro do per&iacute;odo informado: produto, data, quantidade, destino, nota, valor unit&aacute;rio e o valor total por venda. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total vendido em todo o per&iacute;odo agrupados por produto.</span></p>
   <p class="c9 c20"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="2">
      <li class="c6"><span class="c4">Listar investimentos realizados por per&iacute;odo;</span></li>
   </ol>
   <p class="c11"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exibe as seguintes informa&ccedil;&otilde;es referente aos investimentos ocorridos dentro do per&iacute;odo informado: nome, descri&ccedil;&atilde;o, valor unit&aacute;rio, quantidade, data e o valor total por investimentos. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total investido em todo o per&iacute;odo. </span></p>
   <p class="c9"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="3">
      <li class="c6"><span class="c4">Listar despesas realizadas por per&iacute;odo;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente &agrave;s despesas ocorridas dentro do per&iacute;odo informado: nome, descri&ccedil;&atilde;o, valor unit&aacute;rio, quantidade, data e o valor total por despesas. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total das despesas em todo o per&iacute;odo. </span></p>
   <p class="c9"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="4">
      <li class="c6"><span class="c4">Listar plantios realizados por per&iacute;odo;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente aos plantios ocorridos dentro do per&iacute;odo informado: talh&atilde;o, produto, data da semeadura, data do plantio, quantidade de mudas e o valor total por plantio. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total dos plantios em todo o per&iacute;odo.</span></p>
   <p class="c9 c14"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="5">
      <li class="c6"><span class="c4">Listar manejos realizados por per&iacute;odo por talh&atilde;o;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente aos manejos realizados por talh&atilde;o dentro do per&iacute;odo informado: plantio, manejo, data e hora, horas utilizadas, descri&ccedil;&atilde;o, propriedade e o valor total por manejo em cada talh&atilde;o. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total dos manejos em todo o per&iacute;odo.</span></p>
   <p class="c9 c14"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="6">
      <li class="c6"><span class="c4">Listar colheitas realizadas por per&iacute;odo;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente as colheitas realizadas dentro do per&iacute;odo informado: plantio, manejo, data e hora, horas utilizadas, descri&ccedil;&atilde;o, propriedade e o valor total por colheita em cada talh&atilde;o. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total das colheitas em todo o per&iacute;odo.</span></p>
   <p class="c9 c20"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="7">
      <li class="c6"><span class="c4">Listar talh&otilde;es por propriedade;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente aos talh&otilde;es cadastrados para a propriedade: &nbsp;plantio, manejo, data e hora, horas utilizadas, descri&ccedil;&atilde;o, propriedade e o valor total por talh&atilde;o em cada propriedade. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total dos talh&otilde;es em todo o per&iacute;odo.</span></p>
   <p class="c9"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="8">
      <li class="c6"><span class="c4">Listar produtos ativos e inativos por propriedade;</span></li>
   </ol>
   <p class="c11"><span class="c4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exibe as seguintes informa&ccedil;&otilde;es referente aos produtos ativos e inativos cadastrados por propriedade: &nbsp;produto, status e propriedade. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade total de produtos ativos e inativos.</span></p>
   <p class="c9"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="9">
      <li class="c6"><span class="c4">Listar hist&oacute;rico de manejo por plantio;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente aos manejos realizados por plantio dentro do per&iacute;odo informado: plantio, manejo, data e hora, horas utilizadas, descri&ccedil;&atilde;o e o valor total por manejo em cada plantio. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade e o valor total dos manejos em todo o per&iacute;odo.</span></p>
   <p class="c9 c14"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="10">
      <li class="c6"><span class="c4">Listar estoque por propriedade por per&iacute;odo;</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente aos produtos estocados dentro do per&iacute;odo informado: nome, quantidade, data. Ao final do relat&oacute;rio s&atilde;o apresentados a quantidade de produtos totais estocados durante todo o per&iacute;odo.</span></p>
   <p class="c9 c14"><span class="c4"></span></p>
   <ol class="c17 lst-kix_rsc81jtmjihj-2" start="11">
      <li class="c6"><span class="c4">Listar perdas por per&iacute;odo.</span></li>
   </ol>
   <p class="c11 c14"><span class="c4">Exibe as seguintes informa&ccedil;&otilde;es referente &agrave;s perdas ocorridas dentro do per&iacute;odo informado: produto, data, quantidade e motivo da perda. Ao final do relat&oacute;rio &eacute; apresentada a quantidade total perdida durante todo o per&iacute;odo por produto.</span></p>
   <p class="c1"><span class="c8 c3"></span></p>
   <p class="c2"><span class="c3">4.1.10 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 66.62px; height: 66.62px;"><img alt="" src="images/imagesManual/image4.png" style="width: 66.62px; height: 66.62px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span class="c8 c3">Manual</span></p>
   <p class="c2"><span class="c3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="c4">No menu manual o agricultor tem acesso ao manual do usu&aacute;rio. Nele cont&eacute;m todas as informa&ccedil;&otilde;es do funcionamento do sistema.</span></p>
   <p class="c1"><span class="c4"></span></p>
   <p class="c2"><span class="c3">4.1.11 </span><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 65.50px; height: 65.50px;"><img alt="" src="images/imagesManual/image24.png" style="width: 65.50px; height: 65.50px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span><span>&nbsp; </span><span class="c8 c3">Perfil </span></p>
   <p class="c0"><span class="c4">No menu perfil o agricultor pode atualizar as informa&ccedil;&otilde;es inseridas durante o cadastro, inclusive a atualiza&ccedil;&atilde;o da senha. O CPF &eacute; a &uacute;nica informa&ccedil;&atilde;o n&atilde;o edit&aacute;vel do perfil.</span></p>
   <p class="c1"><span class="c12"></span></p>
   <p class="c2"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 686.00px; height: 276.00px;"><img alt="" src="images/imagesManual/image35.png" style="width: 686.00px; height: 276.00px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></p>
   <p class="c2"><span>Ao cancelar a opera&ccedil;&atilde;o, os dados do perfil s&atilde;o exibidos na tela conforme estavam salvos anteriormente.</span></p>
   <p class="c9"><span class="c4"></span></p>
   <p class="c9"><span class="c4"></span></p>
   <p class="c1"><span class="c4"></span></p>
   <div>
      <p class="c9"><span class="c4"></span></p>
   </div>
</div>
@endsection
